// <auto-generated />
namespace Ticketing_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Tickets4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tickets4));
        
        string IMigrationMetadata.Id
        {
            get { return "201810191356544_Tickets4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
